spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**
          filters:
            - AddRequestHeader=Authorization, "#{T(org.springframework.web.server.ServerWebExchange).getRequest().getHeaders().getFirst('Authorization')}"
        
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/login
          filters:
