spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
server:
  port: 8080