name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build all services with Maven
      run: mvn clean install -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build  # Cette étape dépend de l'étape "build"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Run tests
      run: mvn test

  push-images:
    runs-on: ubuntu-latest
    needs: test  # Cette étape dépend de l'étape "test"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker images for all services
      run: |
        docker build -t web-app ./web-app
        docker build -t patient-service ./patient-service
        docker build -t note-service ./note-service
        docker build -t auth ./auth
        docker build -t diabetes-service ./diabetes-service
        docker build -t gateway-service ./gateway-service

    - name: Push Docker images to Docker Hub (optional)
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag web-app $DOCKER_USERNAME/web-app:latest
        docker push $DOCKER_USERNAME/web-app:latest
        docker tag patient-service $DOCKER_USERNAME/patient-service:latest
        docker push $DOCKER_USERNAME/patient-service:latest
        docker tag note-service $DOCKER_USERNAME/note-service:latest
        docker push $DOCKER_USERNAME/note-service:latest
        docker tag auth $DOCKER_USERNAME/auth:latest
        docker push $DOCKER_USERNAME/auth:latest
        docker tag diabetes-service $DOCKER_USERNAME/diabetes-service:latest
        docker push $DOCKER_USERNAME/diabetes-service:latest
        docker tag gateway-service $DOCKER_USERNAME/gateway-service:latest
        docker push $DOCKER_USERNAME/gateway-service:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
